Add try/catch block around method.setAccessible() call since it can throw an InaccessibleObjectException.
  [ERROR] testOSPlugin(org.opennms.systemreport.system.SystemReportPluginIT)  Time elapsed: 0.04 s  <<< ERROR!
  java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getCommittedVirtualMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @65466a6a
          at org.opennms.systemreport.system.SystemReportPluginIT.testOSPlugin(SystemReportPluginIT.java:57)